spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sys_project
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  # https://stackoverflow:com/questions/70036953/spring-boot-2-6-0-spring-fox-3-failed-to-start-bean-documentationpluginsboo
  mvc:
    path-match:
      matching-strategy: ant_path_matcher